services:
  mysql:
    build: ./mysql
    container_name: book-portal-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: book_portal
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  book-portal-be:
    build: ./book-portal-be
    container_name: book-portal-be
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book_portal?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy

  book-portal-fe:
    build: ./book-portal-fe
    container_name: book-portal-fe
    depends_on:
      - book-portal-be

  proxy:
    build: ./nginx
    container_name: book-portal-proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - book-portal-fe
      - book-portal-be

volumes:
  db-data:
