name: Java CI with Maven and CodeQL analyze

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'fix/**'
  pull_request:
    branches: [ master ]

jobs:
  analyze_and_build:
    name: Analyze and Build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    strategy:
      matrix:
        language: [ 'java' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - run: mvn -B package -DskipTests --file pom.xml
        working-directory: ./book-portal-be

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  docker:
    needs: analyze_and_build
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push BE
        uses: docker/build-push-action@v6
        with:
          context: ./book-portal-be
          file: ./book-portal-be/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/book-portal-be:latest
